# Generated by Django 3.1.6 on 2021-03-05 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True)),
                ('cover_picture', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=128)),
                ('sku', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('price_per_unit', models.PositiveIntegerField(default=5000)),
                ('amount_in_stock', models.PositiveIntegerField(default=15)),
                ('picture', models.ImageField(max_length=255, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
        ),
    ]
